### ISSUE TITLE
Delegation of the development of Extensions (OGC API parts) to different OGC API SWGs

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/architecture-dwg#24]
This issue was raised during the 2021-04-19 OGC API - Common SWG meeting.

The question is how to improve the delegation of the development of Extensions (OGC API parts) such that all OGC API SWGs contribute to extensions before they are passed to the OGC API - Common SWG for further development.

**Comment by cportele** [comment]
The OGC mechanism to organize the distributed development of standards in general and including extensions (new requirements classes extending one or more existing requirements classes) are the SWG charters and the task approval process. This is already in place and includes TC-wide presentations/discussion including at a plenary, public comments and the full TC/PC approval process. So, I think the mechanisms for delegation based on consensus are all there.

We should focus the discussion on how to make the distributed development work. With regard to OGC API building blocks, what could help are periodic reports from SWGs working on those building blocks with technical details on what they are working on and in particular design decisions. These could, for example, be provided by the 3-week rule and questions/comments could be discussed by all members in a special session during each Member Meeting, if members want to formalize the process more. This will obviously slow down progress, because some resources are shifted from SWG work to creating the reports and related discussions, but it may be worth it.

Actually, maybe it would also be possible to automate the generation of the SWG reports, since all SWGs use GitHub issues and pull requests to capture all discussion, proposals and decisions. For software products managed in git repositories, if there is a new software release, a common approach is to automatically generate the change log from issues or sometimes PRs/MRs. This requires some conventions regarding content, the use of labels, etc. We could do something similar with our OGC API repos and create regular reports about discussions and decisions using a script (weekly, monthly, before every Member Meeting or every time a new draft release of a standard is tagged by a SWG). This would be inline with the goal of treating the standards more as products.

**Comment by ogcscotts** [comment]
@cportele I like your suggestion. We are also working on an "OC API Blueprint" that highlights the functions of and relationships between the Standards. Adding another view organized around Building Blocks would be useful.

**Comment by ghobona** [comment]
Considering that we now have an OGC Building Blocks Registry, I propose to close this GitHub Issue on 2023-02-13 at 17:00 CET.
